/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentcompanion;

import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.io.*;

/**
 *
 * @author anmol singh sethi
 */
public class stuentsignup extends javax.swing.JFrame {

    /**
     * Creates new form stuentsignup
     */
    public stuentsignup() {
        initComponents();

        setSize(1000, 1000);
        setVisible(true);

        cbdept.removeAllItems();
        try {
            Class.forName("com.mysql.jdbc.Driver");
//            System.out.println("Driver Loading done");

            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/student_companion", "root", "system");
//            System.out.println("Connection Created");

            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
//            System.out.println("Statement Created");

            ResultSet rs = stmt.executeQuery("select * from departments");
            while (rs.next()) {
                String deptname = rs.getString("department");
                cbdept.addItem(deptname);
            }
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tfrollno = new javax.swing.JTextField();
        tfname = new javax.swing.JTextField();
        tffname = new javax.swing.JTextField();
        tfphone = new javax.swing.JTextField();
        tfemail = new javax.swing.JTextField();
        cbday = new javax.swing.JComboBox<>();
        cbmonth = new javax.swing.JComboBox<>();
        cbyear = new javax.swing.JComboBox<>();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        tfphoto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbdept = new javax.swing.JComboBox<>();
        cbcourse = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("enter rollno");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(39, 27, 145, 42);

        jLabel2.setText("name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(39, 76, 79, 31);

        jLabel3.setText("fname");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(39, 120, 79, 30);

        jLabel4.setText("phone");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(39, 182, 67, 27);

        jLabel5.setText("email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(39, 222, 67, 33);

        jLabel6.setText("dob");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(39, 294, 67, 38);

        jLabel7.setText("gender");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(39, 345, 67, 35);

        jLabel8.setText("select photo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(26, 387, 92, 35);

        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 470, 190, 50);
        getContentPane().add(tfrollno);
        tfrollno.setBounds(365, 37, 170, 22);
        getContentPane().add(tfname);
        tfname.setBounds(368, 80, 170, 22);

        tffname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffnameActionPerformed(evt);
            }
        });
        getContentPane().add(tffname);
        tffname.setBounds(345, 124, 190, 22);
        getContentPane().add(tfphone);
        tfphone.setBounds(345, 184, 190, 22);
        getContentPane().add(tfemail);
        tfemail.setBounds(340, 230, 170, 22);

        cbday.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cbday);
        cbday.setBounds(310, 310, 70, 30);

        cbmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(cbmonth);
        cbmonth.setBounds(400, 310, 70, 30);

        cbyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "97", "98", "99", "00", "01", "02", "03", "04" }));
        getContentPane().add(cbyear);
        cbyear.setBounds(500, 310, 80, 30);

        buttonGroup1.add(rbmale);
        rbmale.setText("male");
        getContentPane().add(rbmale);
        rbmale.setBounds(307, 355, 57, 25);

        buttonGroup1.add(rbfemale);
        rbfemale.setText("female");
        rbfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfemaleActionPerformed(evt);
            }
        });
        getContentPane().add(rbfemale);
        rbfemale.setBounds(432, 355, 67, 25);

        jButton2.setText("browse...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(550, 400, 140, 25);
        getContentPane().add(tfphoto);
        tfphoto.setBounds(157, 383, 390, 60);

        jLabel9.setText("Enter Department");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(660, 40, 130, 16);

        jLabel10.setText("Enter Course");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(660, 100, 150, 16);

        cbdept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbdept.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbdeptItemStateChanged(evt);
            }
        });
        getContentPane().add(cbdept);
        cbdept.setBounds(804, 40, 150, 22);

        cbcourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbcourse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbcourseItemStateChanged(evt);
            }
        });
        getContentPane().add(cbcourse);
        cbcourse.setBounds(814, 100, 140, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tffnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffnameActionPerformed

    private void rbfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbfemaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rno = tfrollno.getText();
        String name = tfname.getText();
        String phone = tfphone.getText();
        String fname = tffname.getText();
        String email = tfemail.getText();
        String dob = (String) (cbday.getSelectedItem() + "-" + cbmonth.getSelectedItem() + "-" + cbyear.getSelectedItem());
        String gender = "";
        if (rbmale.isSelected()) {
            gender = "Male";
        } else {
            gender = "Female";
        }

        String password = ((int) (100000 + (999999 - 100000) * Math.random())) + "";
        if(rno.isEmpty()||name.isEmpty()||phone.isEmpty()||fname.isEmpty()||email.isEmpty()||dob.isEmpty()||gender.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter all credentials");
           
        }
        else
        {
          try {
            File f = new File("Student_pics");
            if (!f.exists()) {
                f.mkdir();
            }
            FileOutputStream fos = new FileOutputStream("Student_pics/" + rno + ".jpg");
            FileInputStream fis = new FileInputStream(tfphoto.getText());
            byte b[] = new byte[10000];
            while (true) {
                int r;
                r = fis.read(b, 0, 10000);
                if (r == -1) {
                    break;
                }
                fos.write(b, 0, r);
            }
            fos.close();
            fis.close();

        } catch (Exception e) {
            e.printStackTrace();
        }

        try {
            Class.forName("com.mysql.jdbc.Driver");
//            System.out.println("Driver Loading done");

            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/student_companion", "root", "system");
//            System.out.println("Connection Created");

            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
//            System.out.println("Statement Created");

            ResultSet rs = stmt.executeQuery("select * from student where rollno='" + rno + "'");
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "This rollno already exists");

            } else {
                rs.moveToInsertRow();

                rs.updateString("rollno", rno);

                rs.updateString("name", name);

                rs.updateString("course", cbcourse.getSelectedItem().toString());

                rs.updateString("fname", fname);

                rs.updateString("phone", phone);

                rs.updateString("email", email);

                rs.updateString("dob", dob);

                rs.updateString("gender", gender);

                rs.updateString("password", password);

                rs.updateString("photo", "Student_pics/" + rno + ".jpg");

                rs.insertRow();
                JOptionPane.showMessageDialog(rootPane, "Subject added successfully");
                dispose();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        }
        


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser jf = new JFileChooser();
        int ans = jf.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            String path = jf.getSelectedFile().getPath();
            tfphoto.setText(path);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbcourseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbcourseItemStateChanged

    }//GEN-LAST:event_cbcourseItemStateChanged

    private void cbdeptItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbdeptItemStateChanged

        String s = (String) cbdept.getSelectedItem();
        cbcourse.removeAllItems();
        try {
            Class.forName("com.mysql.jdbc.Driver");
//            System.out.println("Driver Loading done");

            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/student_companion", "root", "system");
//            System.out.println("Connection Created");

            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,
                    ResultSet.CONCUR_UPDATABLE);
//            System.out.println("Statement Created");

            ResultSet rs = stmt.executeQuery("select * from courses where department='" + s + "'");
            while (rs.next()) {

                cbcourse.addItem(rs.getString("coursename"));
            }
            stmt.close();
            rs.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cbdeptItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stuentsignup.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stuentsignup.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stuentsignup.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stuentsignup.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stuentsignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbcourse;
    private javax.swing.JComboBox<String> cbday;
    private javax.swing.JComboBox<String> cbdept;
    private javax.swing.JComboBox<String> cbmonth;
    private javax.swing.JComboBox<String> cbyear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tffname;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfphone;
    private javax.swing.JTextField tfphoto;
    private javax.swing.JTextField tfrollno;
    // End of variables declaration//GEN-END:variables
}
